### ISSUE TITLE
"brew install datasette" should put "datasette" on the PATH (maybe /usr/local/bin/datasette)

### ISSUE THREAD

**Issue by simonw** [simonw/homebrew-datasette#2]
Following #1. This almost works:
```
brew tap simonw/datasette
brew install datasette
```
There's just one thing missing: After you run this:
```
$ which datasette
datasette not found
```
But it's installed - you can run it like this:
```
$ /usr/local/Cellar/datasette/0.46/libexec/bin/datasette --version
datasette, version 0.46
```
My `/usr/local/bin` directory is full of symlinks to stuff in the `/usr/local/Cellar` folder:
```
$ ls -lah /usr/local/bin | grep Cellar
lrwxr-xr-x    1 simon  admin    35B Aug  8 20:20 2to3 -> ../Cellar/python@3.8/3.8.5/bin/2to3
lrwxr-xr-x    1 simon  admin    39B Aug  8 20:20 2to3-3.8 -> ../Cellar/python@3.8/3.8.5/bin/2to3-3.8
lrwxr-xr-x    1 simon  admin    38B Jun 28 13:55 ada_count -> ../Cellar/sloccount/2.26/bin/ada_count
lrwxr-xr-x    1 simon  admin    38B Jun 28 13:55 asm_count -> ../Cellar/sloccount/2.26/bin/asm_count
lrwxr-xr-x    1 simon  admin    36B Apr 21 13:27 autoconf -> ../Cellar/autoconf/2.69/bin/autoconf
lrwxr-xr-x    1 simon  admin    38B Apr 21 13:27 autoheader -> ../Cellar/autoconf/2.69/bin/autoheader
lrwxr-xr-x    1 simon  admin    36B Apr 21 13:27 autom4te -> ../Cellar/autoconf/2.69/bin/autom4te
lrwxr-xr-x    1 simon  admin    36B Aug  8 20:23 autopoint -> ../Cellar/gettext/0.21/bin/autopoint
lrwxr-xr-x    1 simon  admin    38B Apr 21 13:27 autoreconf -> ../Cellar/autoconf/2.69/bin/autoreconf
lrwxr-xr-x    1 simon  admin    36B Apr 21 13:27 autoscan -> ../Cellar/autoconf/2.69/bin/autoscan
lrwxr-xr-x    1 simon  admin    38B Apr 21 13:27 autoupdate -> ../Cellar/autoconf/2.69/bin/autoupdate
lrwxr-xr-x    1 simon  admin    38B Jun 28 13:55 awk_count -> ../Cellar/sloccount/2.26/bin/awk_count
lrwxr-xr-x    1 simon  admin    41B Apr 28 08:00 bjoentegaard -> ../Cellar/libde265/1.0.5/bin/bjoentegaard
...
```
But for some reason `datasette` didn't get a symlink. I'm stuck on how to fix it.

**Comment by mrchrisadams** [comment]
Based on me looking at youtube-dl, and what @webology said on twitter, it looks like you need to explicitly link the binary after install.

Where you have this code:

```ruby
def install
    virtualenv_install_with_resources
    bin.install "datasette"
  end
``` 

The AWSCLI example [explicitly links the build path](https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb#L32):


```ruby
def install
    venv = virtualenv_create(libexec, "python3")
    system libexec/"bin/pip", "install", "-v", "-r", "requirements.txt",
                              "--ignore-installed", buildpath
    system libexec/"bin/pip", "uninstall", "-y", "awscli"
    venv.pip_install_and_link buildpath
```

It might also be worth looking at how youtube-dl lists dependencies - I've noticed they also do a thing where they refer to the [generated release on github rather than referring to each dep explicitly in the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb#L4-L22)

```ruby
class YoutubeDl < Formula
  desc "Download YouTube videos from the command-line"
  homepage "https://ytdl-org.github.io/youtube-dl/"
  url "https://github.com/ytdl-org/youtube-dl/releases/download/2020.07.28/youtube-dl-2020.07.28.tar.gz"
  sha256 "1fb3e34d80400464e55aeeb61256c36468116ad9efe82543b437a777a2efc7c5"

  # snip  

  def install
    system "make", "PREFIX=#{prefix}" if build.head?
    bin.install "youtube-dl"
    man1.install "youtube-dl.1"
    bash_completion.install "youtube-dl.bash-completion"
    zsh_completion.install "youtube-dl.zsh" => "_youtube-dl"
    fish_completion.install "youtube-dl.fish"
  end
````
 

I have to dash out the door, so haven't had a chance to test these yet, but when I'm back later today, I'm happy to give it a go.

**Comment by dracos** [comment]
But running `virtualenv_install_with_resources`, according to https://docs.brew.sh/Python-for-Formula-Authors, is meant to be equivalent to `virtualenv_create`, `venv.pip_install resources`, `pip_install_and_link buildpath`.
You can run brew install with --debug, that might show something?

**Comment by dracos** [comment]
https://github.com/Homebrew/brew/blob/b447f57e364a5b56d1dec244b91e65151b046635/Library/Homebrew/language/python.rb#L282-L290 (and caller) seems to be straightforward enough - it does pip install resources, then compares the bin before and after normal pip install for what to symlink.

**Comment by dracos** [comment]
Ah so it's because you have datasette listed as a resource. So it gets installed in the `venv.pip_install resources` step, checks what bin scripts are there, runs `pip install buildpath`, then sees nothing has changed and links nothing. It looks like brew expects to run pip install on all your resources, then has unpacked your zip file to run pip install directly on that (the package itself), so you don't want to also list datasette as a resource of itself, maybe?

**Comment by simonw** [comment]
I tried messing around with `brew link`:

```
$ brew unlink datasette && brew link datasette
Unlinking /usr/local/Cellar/datasette/0.46... 0 symlinks removed
Linking /usr/local/Cellar/datasette/0.46... 0 symlinks created
```

Seems to confirm the theory that the symlinks aren't being created.

I like @dracos idea that "it's because you have datasette listed as a resource". Trying that next.

**Comment by simonw** [comment]
Interesting new error running `brew install datasette`:
```
==> /usr/local/Cellar/datasette/0.46/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/datasette-20200811-85547-vqxd
Error: An exception occurred within a child process:
  Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (datasette, /usr/local/Cellar/datasette/0.46/bin/datasette)
```
Trying `brew install datasette --debug` to see if I get any new clues.

**Comment by dracos** [comment]
Are you clearing out between each install? Who knows what your experiments up to now have left in there if not, if you've done something that's manually copied a file where brew actually wants to put a directory, for example.

**Comment by simonw** [comment]
With `--debug` I got dropped into an interactive mode at that error, here's what I got from it:
```
cp -pR /private/tmp/d20200811-91455-1wo0jpe/websockets-8.1/. /private/tmp/datasette--websockets-20200811-91455-1mwzkm1/websockets-8.1
==> /usr/local/Cellar/datasette/0.46/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/datasette--websockets-20200811-91455-1mwzkm1/we
==> /usr/local/Cellar/datasette/0.46/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/datasette-20200811-91455-2djlri/datasette-0.46
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:529:in `rename'
Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (datasette, /usr/local/Cellar/datasette/0.46/bin/datasette)
Choose an action: Multiple options match: raise ignore backtrace irb shell
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:529:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:529:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:520:in `mv'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:121:in `install_p'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:99:in `block in install'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:80:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:80:in `install'
/usr/local/Homebrew/Library/Taps/simonw/homebrew-datasette/Formula/datasette.rb:123:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:24:in `block in install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:94:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:24:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:174:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1187:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2174:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:494:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2173:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:112:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:107:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:82:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2153:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1180:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:142:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:494:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:137:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:226:in `<main>'
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
simon@Simons-MacBook-Pro datasette-0.46 % ls
MANIFEST.in		README.md		datasette.egg-info	setup.py
PKG-INFO		datasette		setup.cfg		versioneer.py
simon@Simons-MacBook-Pro datasette-0.46 % pwd
/private/tmp/datasette-20200811-91455-2djlri/datasette-0.46
simon@Simons-MacBook-Pro datasette-0.46 % ls -lah
total 248
drwxr-xr-x  11 simon  admin   352B Aug 11 08:33 .
drwx------   3 simon  admin    96B Aug 11 08:33 ..
drwxr-xr-x   4 simon  admin   128B Aug 11 08:38 .brew_home
-rw-r--r--   1 simon  admin    89B Aug  9 09:30 MANIFEST.in
-rw-r--r--   1 simon  admin    22K Aug  9 09:38 PKG-INFO
-rw-r--r--   1 simon  admin    20K Aug  9 09:30 README.md
drwxr-xr-x  24 simon  admin   768B Aug  9 09:38 datasette
drwxr-xr-x   8 simon  admin   256B Aug  9 09:38 datasette.egg-info
-rw-r--r--   1 simon  admin   263B Aug  9 09:38 setup.cfg
-rw-r--r--   1 simon  admin   2.7K Aug  9 09:30 setup.py
-rw-r--r--   1 simon  admin    67K Aug  9 09:30 versioneer.py
simon@Simons-MacBook-Pro datasette-0.46 % pwd
/private/tmp/datasette-20200811-91455-2djlri/datasette-0.46
```

**Comment by dracos** [comment]
What is in `/usr/local/Cellar/datasette/0.46/bin/` though? I assume you have a file there, whereas brew in this install proecss is wanting to put the whole datasette directory there (dunno why, who can say).

**Comment by simonw** [comment]
I ran `brew cleanup` so it's gone. Running `brew install datasette --debug` again now, will report back on `/usr/local/Cellar/datasette/` when it finishes (or breaks).

**Comment by simonw** [comment]
So this is interesting. This time I picked option 2 for "ignore"... and the installation completed successfully!
```
Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (datasette, /usr/local/Cellar/datasette/0.46/bin/datasette)
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
🍺  /usr/local/Cellar/datasette/0.46: 1,977 files, 27.4MB, built in 2 minutes 40 seconds
$ datasette --version
datasette, version 0.46
```
I'm suspicious that I may indeed have made a mess of my environment.

**Comment by simonw** [comment]
I have a good hunch about this one...

**Comment by dracos** [comment]
Sorry, yes, I assumed you'd already removed that debugging line. (Have you heard of branches, they're this cool feature ;) )

**Comment by simonw** [comment]
Yes! It worked! Thanks for the help @dracos.

**Comment by simonw** [comment]
Wrote this all up in https://github.com/simonw/til/blob/master/homebrew/packaging-python-cli-for-homebrew.md
